<template>
  <EasyDataTable
    buttons-pagination
    alternating
    border-cell

    :headers="headers"
    :items="items"
  />
</template>

<script setup lang="ts">
import type { Header, Item } from "vue3-easy-data-table";

    const headers: Header[] = [
      { text: "Name", value: "name" },
      { text: "Height (cm)", value: "height", sortable: true },
      { text: "Weight (kg)", value: "weight", sortable: true },
      { text: "Age", value: "age", sortable: true }
    ];

    const items: Item[] = [
      { "name": "ACurry", "height": 178, "weight": 77, "age": 20 },
      { "name": "James", "height": 180, "weight": 75, "age": 21 },
      { "name": "James", "height": 180, "weight": 75, "age": 22 },
      { "name": "James", "height": 180, "weight": 75, "age": 23 },
      { "name": "James", "height": 180, "weight": 75, "age": 24 },
      { "name": "James", "height": 180, "weight": 75, "age": 24 },
      { "name": "James", "height": 180, "weight": 75, "age": 25 },
      { "name": "James", "height": 180, "weight": 75, "age": 24 },
      { "name": "James", "height": 180, "weight": 75, "age": 25 },
      { "name": "James", "height": 180, "weight": 75, "age": 24 },
      { "name": "James", "height": 180, "weight": 75, "age": 25 },
      { "name": "James", "height": 180, "weight": 75, "age": 24 },
      { "name": "James", "height": 180, "weight": 75, "age": 25 },
      { "name": "James", "height": 180, "weight": 75, "age": 24 },
      { "name": "James", "height": 180, "weight": 75, "age": 25 },
      { "name": "James", "height": 180, "weight": 75, "age": 24 },
      { "name": "James", "height": 180, "weight": 75, "age": 25 },
      { "name": "James", "height": 180, "weight": 75, "age": 24 },
      { "name": "James", "height": 180, "weight": 75, "age": 25 },
      { "name": "James", "height": 180, "weight": 75, "age": 24 },
      { "name": "James", "height": 180, "weight": 75, "age": 25 },
      { "name": "James", "height": 180, "weight": 75, "age": 24 },
      { "name": "James", "height": 180, "weight": 75, "age": 25 },
      { "name": "James", "height": 180, "weight": 75, "age": 24 },
      { "name": "James", "height": 180, "weight": 75, "age": 25 },
      { "name": "James", "height": 180, "weight": 75, "age": 24 },
      { "name": "James", "height": 180, "weight": 75, "age": 25 },
      { "name": "James", "height": 180, "weight": 75, "age": 24 },
      { "name": "James", "height": 180, "weight": 75, "age": 25 },
      { "name": "James", "height": 180, "weight": 75, "age": 24 },
      { "name": "James", "height": 180, "weight": 75, "age": 25 },
      { "name": "James", "height": 180, "weight": 75, "age": 24 },
      { "name": "James", "height": 180, "weight": 75, "age": 25 },
      { "name": "James", "height": 180, "weight": 75, "age": 24 },
      { "name": "James", "height": 180, "weight": 75, "age": 25 },
      { "name": "James", "height": 180, "weight": 75, "age": 26 },
      { "name": "James", "height": 180, "weight": 75, "age": 27 },
      { "name": "James", "height": 180, "weight": 75, "age": 28 },
      { "name": "James", "height": 180, "weight": 75, "age": 29 },
      { "name": "James", "height": 180, "weight": 75, "age": 30 },
      { "name": "James", "height": 180, "weight": 75, "age": 31 },
      { "name": "James", "height": 180, "weight": 75, "age": 26 },
      { "name": "James", "height": 180, "weight": 75, "age": 27 },
      { "name": "James", "height": 180, "weight": 75, "age": 28 },
      { "name": "James", "height": 180, "weight": 75, "age": 29 },
      { "name": "James", "height": 180, "weight": 75, "age": 30 },
      { "name": "James", "height": 180, "weight": 75, "age": 31 },
      { "name": "James", "height": 180, "weight": 75, "age": 26 },
      { "name": "James", "height": 180, "weight": 75, "age": 27 },
      { "name": "James", "height": 180, "weight": 75, "age": 28 },
      { "name": "James", "height": 180, "weight": 75, "age": 29 },
      { "name": "James", "height": 180, "weight": 75, "age": 30 },
      { "name": "James", "height": 180, "weight": 75, "age": 31 },
      { "name": "James", "height": 180, "weight": 75, "age": 26 },
      { "name": "James", "height": 180, "weight": 75, "age": 27 },
      { "name": "James", "height": 180, "weight": 75, "age": 28 },
      { "name": "James", "height": 180, "weight": 75, "age": 29 },
      { "name": "James", "height": 180, "weight": 75, "age": 30 },
      { "name": "James", "height": 180, "weight": 75, "age": 31 },
      { "name": "James", "height": 180, "weight": 75, "age": 26 },
      { "name": "James", "height": 180, "weight": 75, "age": 27 },
      { "name": "James", "height": 180, "weight": 75, "age": 28 },
      { "name": "James", "height": 180, "weight": 75, "age": 29 },
      { "name": "James", "height": 180, "weight": 75, "age": 30 },
      { "name": "James", "height": 180, "weight": 75, "age": 31 },
      { "name": "James", "height": 180, "weight": 75, "age": 26 },
      { "name": "James", "height": 180, "weight": 75, "age": 27 },
      { "name": "James", "height": 180, "weight": 75, "age": 28 },
      { "name": "James", "height": 180, "weight": 75, "age": 29 },
      { "name": "James", "height": 180, "weight": 75, "age": 30 },
      { "name": "James", "height": 180, "weight": 75, "age": 31 },
      { "name": "James", "height": 180, "weight": 75, "age": 26 },
      { "name": "James", "height": 180, "weight": 75, "age": 27 },
      { "name": "James", "height": 180, "weight": 75, "age": 28 },
      { "name": "James", "height": 180, "weight": 75, "age": 29 },
      { "name": "James", "height": 180, "weight": 75, "age": 30 },
      { "name": "James", "height": 180, "weight": 75, "age": 31 },
      { "name": "James", "height": 180, "weight": 75, "age": 26 },
      { "name": "James", "height": 180, "weight": 75, "age": 27 },
      { "name": "James", "height": 180, "weight": 75, "age": 28 },
      { "name": "James", "height": 180, "weight": 75, "age": 29 },
      { "name": "James", "height": 180, "weight": 75, "age": 30 },
      { "name": "James", "height": 180, "weight": 75, "age": 31 },
      { "name": "James", "height": 180, "weight": 75, "age": 26 },
      { "name": "James", "height": 180, "weight": 75, "age": 27 },
      { "name": "James", "height": 180, "weight": 75, "age": 28 },
      { "name": "James", "height": 180, "weight": 75, "age": 29 },
      { "name": "James", "height": 180, "weight": 75, "age": 30 },
      { "name": "James", "height": 180, "weight": 75, "age": 31 },
      { "name": "James", "height": 180, "weight": 75, "age": 26 },
      { "name": "James", "height": 180, "weight": 75, "age": 27 },
      { "name": "James", "height": 180, "weight": 75, "age": 28 },
      { "name": "James", "height": 180, "weight": 75, "age": 29 },
      { "name": "James", "height": 180, "weight": 75, "age": 30 },
      { "name": "James", "height": 180, "weight": 75, "age": 31 },
      { "name": "James", "height": 180, "weight": 75, "age": 26 },
      { "name": "James", "height": 180, "weight": 75, "age": 27 },
      { "name": "James", "height": 180, "weight": 75, "age": 28 },
      { "name": "James", "height": 180, "weight": 75, "age": 29 },
      { "name": "James", "height": 180, "weight": 75, "age": 30 },
      { "name": "James", "height": 180, "weight": 75, "age": 31 },
      { "name": "James", "height": 180, "weight": 75, "age": 26 },
      { "name": "James", "height": 180, "weight": 75, "age": 27 },
      { "name": "James", "height": 180, "weight": 75, "age": 28 },
      { "name": "James", "height": 180, "weight": 75, "age": 29 },
      { "name": "James", "height": 180, "weight": 75, "age": 30 },
      { "name": "James", "height": 180, "weight": 75, "age": 31 },
      { "name": "James", "height": 180, "weight": 75, "age": 26 },
      { "name": "James", "height": 180, "weight": 75, "age": 27 },
      { "name": "James", "height": 180, "weight": 75, "age": 28 },
      { "name": "James", "height": 180, "weight": 75, "age": 29 },
      { "name": "James", "height": 180, "weight": 75, "age": 30 },
      { "name": "James", "height": 180, "weight": 75, "age": 31 },
      { "name": "James", "height": 180, "weight": 75, "age": 26 },
      { "name": "James", "height": 180, "weight": 75, "age": 27 },
      { "name": "James", "height": 180, "weight": 75, "age": 28 },
      { "name": "James", "height": 180, "weight": 75, "age": 29 },
      { "name": "James", "height": 180, "weight": 75, "age": 30 },
      { "name": "James", "height": 180, "weight": 75, "age": 31 },
      { "name": "James", "height": 180, "weight": 75, "age": 26 },
      { "name": "James", "height": 180, "weight": 75, "age": 27 },
      { "name": "James", "height": 180, "weight": 75, "age": 28 },
      { "name": "James", "height": 180, "weight": 75, "age": 29 },
      { "name": "James", "height": 180, "weight": 75, "age": 30 },
      { "name": "James", "height": 180, "weight": 75, "age": 31 },
      { "name": "James", "height": 180, "weight": 75, "age": 25 },
      { "name": "James", "height": 180, "weight": 75, "age": 26 },
      { "name": "James", "height": 180, "weight": 75, "age": 27 },
      { "name": "James", "height": 180, "weight": 75, "age": 28 },
      { "name": "James", "height": 180, "weight": 75, "age": 29 },
      { "name": "James", "height": 180, "weight": 75, "age": 30 },
      { "name": "James", "height": 180, "weight": 75, "age": 31 },
      { "name": "Jordan", "height": 181, "weight": 73, "age": 32 }
    ];

</script>

